//! Post-generation hooks: chmod scripts, init git, optional bootstrap.
//!
//! All hooks are best-effort and never fail the render — they print warnings and continue.
//! Each hook is also a no-op if its preconditions aren't met (e.g. `git_init` without git
//! on PATH).

use std::path::Path;
use std::process::Command;

use tracing::warn;

use crate::error::Result;
use crate::recipe::Recipe;

/// Mark known shell scripts as executable on Unix.
pub fn after_render(project_root: &Path, _recipe: &Recipe) -> Result<()> {
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let candidates = [
            "manage.py",
            "compose/local/django/start",
            "compose/local/django/celery/worker/start",
            "compose/local/django/celery/beat/start",
            "compose/local/django/celery/flower/start",
            "compose/production/django/start",
            "compose/production/django/entrypoint",
            "compose/production/postgres/maintenance/_sourced/constants.sh",
            "compose/production/postgres/maintenance/backup",
            "compose/production/postgres/maintenance/restore",
            "compose/production/postgres/maintenance/backups",
            "compose/production/postgres/maintenance/countbackups",
            "compose/production/postgres/maintenance/rmbackup",
            "compose/production/traefik/start",
        ];
        for rel in candidates {
            let p = project_root.join(rel);
            if p.exists() {
                let mut perms = match std::fs::metadata(&p).map(|m| m.permissions()) {
                    Ok(perms) => perms,
                    Err(err) => {
                        warn!(?p, %err, "could not read metadata for chmod");
                        continue;
                    }
                };
                perms.set_mode(0o755);
                if let Err(err) = std::fs::set_permissions(&p, perms) {
                    warn!(?p, %err, "could not chmod +x");
                }
            }
        }
    }
    Ok(())
}

/// Initialize the selected version-control system in the generated project + create an
/// initial commit. Best-effort: missing binary → no-op + warning.
pub fn vcs_init(project_root: &Path, vcs: crate::recipe::VersionControl) -> Result<()> {
    use crate::recipe::VersionControl::*;
    match vcs {
        Git => init_git(project_root),
        Jj => init_jj(project_root),
        Hg => init_hg(project_root),
        None => {}
    }
    Ok(())
}

/// Backwards-compatible alias — pass through to the generic dispatcher with Git.
pub fn git_init(project_root: &Path) -> Result<()> {
    vcs_init(project_root, crate::recipe::VersionControl::Git)
}

fn init_git(project_root: &Path) {
    if which("git").is_none() {
        warn!("git not on PATH; skipping VCS init");
        return;
    }
    let _ = Command::new("git")
        .arg("init")
        .arg("--initial-branch=main")
        .current_dir(project_root)
        .output();
    let _ = Command::new("git")
        .arg("add")
        .arg(".")
        .current_dir(project_root)
        .output();
    let _ = Command::new("git")
        .arg("-c")
        .arg("user.email=bakery@local")
        .arg("-c")
        .arg("user.name=django-bakery")
        .arg("commit")
        .arg("-m")
        .arg("chore: initial commit (generated by django-bakery)")
        .current_dir(project_root)
        .output();
}

fn init_jj(project_root: &Path) {
    if which("jj").is_none() {
        warn!("jj not on PATH; falling back to git");
        init_git(project_root);
        return;
    }
    // jj works either standalone or co-located with a git repo. We use git colocation
    // so the project also has a git remote target out of the box.
    let _ = Command::new("git")
        .arg("init")
        .arg("--initial-branch=main")
        .current_dir(project_root)
        .output();
    let _ = Command::new("jj")
        .arg("git")
        .arg("init")
        .arg("--colocate")
        .current_dir(project_root)
        .output();
    let _ = Command::new("jj")
        .arg("commit")
        .arg("--message")
        .arg("chore: initial commit (generated by django-bakery)")
        .current_dir(project_root)
        .output();
}

fn init_hg(project_root: &Path) {
    if which("hg").is_none() {
        warn!("hg not on PATH; skipping VCS init");
        return;
    }
    let _ = Command::new("hg")
        .arg("init")
        .current_dir(project_root)
        .output();
    let _ = Command::new("hg")
        .arg("add")
        .current_dir(project_root)
        .output();
    let _ = Command::new("hg")
        .arg("commit")
        .arg("-m")
        .arg("chore: initial commit (generated by django-bakery)")
        .arg("-u")
        .arg("django-bakery <bakery@local>")
        .current_dir(project_root)
        .output();
}

/// Optional: run `uv sync`, `pnpm install`, `pre-commit install`.
pub fn bootstrap(project_root: &Path, recipe: &Recipe) -> Result<()> {
    if which("uv").is_some() {
        let _ = Command::new("uv")
            .arg("sync")
            .current_dir(project_root)
            .status();
    }
    if matches!(
        recipe.frontend,
        crate::recipe::Frontend::React | crate::recipe::Frontend::Nuxt
    ) && which("pnpm").is_some()
    {
        let frontend_dir = project_root.join("frontend");
        if frontend_dir.exists() {
            let _ = Command::new("pnpm")
                .arg("install")
                .current_dir(&frontend_dir)
                .status();
        }
    }
    if recipe.use_pre_commit && which("uv").is_some() {
        let _ = Command::new("uv")
            .arg("run")
            .arg("pre-commit")
            .arg("install")
            .current_dir(project_root)
            .status();
    }
    Ok(())
}

fn which(bin: &str) -> Option<String> {
    let paths = std::env::var_os("PATH")?;
    for p in std::env::split_paths(&paths) {
        let candidate = p.join(bin);
        if candidate.exists() {
            return Some(candidate.to_string_lossy().into_owned());
        }
        let with_exe = p.join(format!("{bin}.exe"));
        if with_exe.exists() {
            return Some(with_exe.to_string_lossy().into_owned());
        }
    }
    None
}
